### ISSUE TITLE
- [MBProgressHUD show:] issue in 0.9.1

### ISSUE THREAD

**Issue by fergalrooney** [jdg/MBProgressHUD#279]
I am seeing an issue in 0.9.1. When I add the progress view using <code>MBProgressHUD.showHUDAddedTo(self.view, animated: false)</code>
and retain the returned reference, calling instance method <b>hide:</b> hides the view successfully, but when I call the <b>show:</b> instance method, the progress view never shows again. I reverted back to version 0.9.0 and it works fine again. Here is the order of method calls required to reproduce.

<code>self._myProgressHUD = MBProgressHUD.showHUDAddedTo(self.view, animated: false)</code>
<code>_myProgressHUD.hide(false)</code>
<code>_myProgressHUD.show(false)</code>

**Comment by ekimovnikolay** [comment]
Got the same problem. 
in 0.9.1 line [self setNeedsDisplay] was removed from method - (void)show:(BOOL)animated ; And smth else was changed. Smth that breaks the functionality.

**Comment by matej** [comment]
This is actually expected behavior. `MBProgressHUD.showHUDAddedTo` sets `removeFromSuperViewOnHide` so before you can re-show it you need to re-add it to the view hierarchy. If you want to reuse it just set `hud.removeFromSuperViewOnHide = NO;` right after showing it the first time, or just init and add the hud manually. 

I added some documentation that should clarify this behavior in  f0c6d4d.
