### ISSUE TITLE
Same appeareance as the old ProgressHud Black view, white letters?

### ISSUE THREAD

**Issue by omarojo** [jdg/MBProgressHUD#364]
I spent a considerable amount of time trying to disable the blurr thing, and just trying to make it look exactly as it was before... just black transparent background with white spinning wheel and white text.

I just want to confirm.. this is not possible anymore ?

**Comment by matej** [comment]
It should be possible. That's still the default appearance for iOS 6. You can just check how it's set up for pre iOS 7 and do the same.

**Comment by matej** [comment]
Or you can use the legacy version, if you don't need any of the new features.

**Comment by yas375** [comment]
@omarojo I'm using the latest version of this lib (605f9d7) and was able do get dark semi-tranparent background.

```swift
hud.backgroundView.color = UIColor(white: 0, alpha: 0.5)
```

The next line you probably don't need because it's already solid color by [default](https://github.com/jdg/MBProgressHUD/blob/605f9d762ec5a924a5a2b8331d1aa7595a17ab8e/MBProgressHUD.m#L315) but since you've mentioned you are getting blurry bg:

```
hud.backgroundView.style = .SolidColor
```
