### ISSUE TITLE
If I use a custom view to display HUD, there will be errors.

### ISSUE THREAD

**Issue by linjiaxing1992** [jdg/MBProgressHUD#526]
I found I use a custom UIView to display HUD  instead of UIImageView，HUD's custom view will not show or be biased.

**Comment by matej** [comment]
Be sure the custom view reports its intrinsic content size, so the HUD can size correctly.

**Comment by linjiaxing1992** [comment]
@matej This is my code：
```objc
UIView *view = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 60, 60)];
UILabel *label = [UILabel new];
label.backgroundColor = [UIColor grayColor];
label.frame = view.frame;
label.text = @"ssssss";
label.textAlignment = NSTextAlignmentCenter;
[view addSubview:label];

MBProgressHUD *hud = [MBProgressHUD showHUDAddedTo:self.view animated:YES];
hud.mode = MBProgressHUDModeCustomView;
hud.customView = view;
hud.label.text = @"自定义view";
hud.detailsLabel.text = @"view";
hud.removeFromSuperViewOnHide = YES;
[hud hideAnimated:YES afterDelay:1.0];
```
Results the following：      
![picture](http://opbgz9a4w.bkt.clouddn.com/QQ20180227-103812.png)

I found this problem in 1.1.0 and 1.0.0, not in the old version.

Thank U！

**Comment by matej** [comment]
It's not an issue with the old version because that does not use auto layout. This one does. 

The problem here is that the view you are adding (`hud.customView = view;`) does not correctly report its intrinsic size to auto layout. If you added the label directly it probably would work. Try setting up autolayout constraints between the label and wrapper view, then it should work.

**Comment by linjiaxing1992** [comment]
Create objects without setting coordinates。
